// js/etapes.js
const ETAPES = [
    { numero: 1,  pays: 'Argentine',       ville1: 'Santa Florentina',        ville2: 'Santa Florentina' },
    { numero: 2,  pays: 'Brésil',          ville1: 'Uribici',                 ville2: 'Uribici' },
    { numero: 3,  pays: 'Vénézuéla',       ville1: 'Lagunillas',              ville2: 'Mérida' },
    { numero: 4,  pays: 'Colombie',        ville1: 'Doradal',                 ville2: 'Rionegro' },
    { numero: 5,  pays: 'Jamaïque',        ville1: 'Montego Bay',             ville2: 'Montego Bay' },
    { numero: 6,  pays: 'Equateur',        ville1: 'Ibarra',                  ville2: 'Ibarra' },
    { numero: 7,  pays: 'Bélize',          ville1: 'Armenia',                 ville2: 'Pine Creek' },
    { numero: 8,  pays: 'Honduras',        ville1: 'Lamaní',                  ville2: 'Lamaní' },
    { numero: 9,  pays: 'Guatemala',       ville1: 'Salamá',                  ville2: 'Ciudad de Guatemala' },
    { numero: 10, pays: 'Cuba',            ville1: 'Havana',                  ville2: 'Havana' },
    { numero: 11, pays: 'Mexique',         ville1: 'Monterrey',               ville2: 'Monterrey' },
    { numero: 12, pays: 'USA',             ville1: 'Hemet',                   ville2: 'Big Bear City' },
    { numero: 13, pays: 'Canada',          ville1: 'Jasper',                  ville2: 'Marmot Basin' },
    { numero: 14, pays: 'NZ',              ville1: 'Masterton',               ville2: 'Admiral Hill' },
    { numero: 15, pays: 'Australie',       ville1: 'Corryong',                ville2: 'Mount Kosciuszko' },
    { numero: 16, pays: 'Tonga',           ville1: "Ha'apai",                 ville2: '' },
    { numero: 17, pays: 'Papouasie',       ville1: 'Tubusereia',              ville2: 'Kokoda' },
    { numero: 18, pays: 'Indonésie',       ville1: 'Banjuwangi',              ville2: 'Tjluring' },
    { numero: 19, pays: 'Malaisie',        ville1: 'Kuala Kubu Baru',         ville2: 'Hulu Selangor' },
    { numero: 20, pays: 'Philippines',     ville1: 'Calamba',                 ville2: 'Angeles' },
    { numero: 21, pays: 'Thaïlande',       ville1: 'Chiang Mai',              ville2: 'Ban Pa Khui' },
    { numero: 22, pays: 'Viêt Nam',        ville1: 'Nha Trang',               ville2: 'Da Lat' },
    { numero: 23, pays: 'Taïwan',          ville1: 'Nantou',                  ville2: 'Sun Moon Lake' },
    { numero: 24, pays: 'Japon',           ville1: 'Saitama',                 ville2: 'Chichibu' },
    { numero: 25, pays: 'Corée du Sud',    ville1: 'Noryang-ri',              ville2: 'Namyang-ri' },
    { numero: 26, pays: 'Chine',           ville1: 'Wuzhishan',               ville2: 'Changjiang' },
    { numero: 27, pays: 'Bhoutan',         ville1: 'Trashigang',              ville2: 'Ura Park' },
    { numero: 28, pays: 'Népal',           ville1: 'Bhojpur',                 ville2: 'Phera-Everest Gateway' },
    { numero: 29, pays: 'Inde',            ville1: 'Gorubathan',              ville2: 'Darjeeling' },
    { numero: 30, pays: 'Pakistan',        ville1: 'Faisal Hills',            ville2: 'Faisal Hills' },
    { numero: 31, pays: 'Iran',            ville1: 'Baneh',                   ville2: 'Ebrahimeh' },
    { numero: 32, pays: 'Turquie',         ville1: 'Zephyrium',               ville2: 'Lampron' },
    { numero: 33, pays: 'Israël',          ville1: 'Jerusalem',               ville2: 'Jerusalem' },
    { numero: 34, pays: 'Jordanie',        ville1: "Ma'an",                   ville2: 'Petra' },
    { numero: 35, pays: 'Arabie saoudite', ville1: 'Maraya',                  ville2: 'Skyviews of Harrat Uwayrid' },
    { numero: 36, pays: 'Bahreïn',         ville1: 'Manama',                  ville2: 'Al Jazair' },
    { numero: 37, pays: 'Qatar',           ville1: 'Dukhan',                  ville2: 'Doha' },
    { numero: 38, pays: 'UAE',             ville1: 'Al Fujairah',             ville2: 'Jebel Jais' },
    { numero: 39, pays: 'Oman',            ville1: 'Alhaffa',                 ville2: 'Ittin' },
    { numero: 40, pays: 'Égypte',          ville1: 'Beni Suef',               ville2: 'Pyramids of Gizeh' }
];